---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "SDS348 Fall 2019"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
---
```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
library(tidyverse)
library(plotROC) 
library(pROC)
library(MASS)
library(ggplot2)
library(glmnet)
```
##Min Jo (Andrew) Lee ml45932
```{R eval=F}
data(package = .packages(all.available = TRUE))
```
#0. (5 pts) Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph.
```{R}
getwd()
heart<-read.csv("heart.csv",TRUE,",")
head(heart,10)
```
I used the heart disease data set that dates from 1988 in Cleveland. Age is age in years. Sex is divided into female (0) and male (1). cp is chest pain type (typical angina, atypical angina, non-angina, or asymptomatic angina); but I don't know which one is which. trestbps is resting blood pressure (mm Hg). chol is serum cholesterol (mg/dl). thalach is maximum heart rate achieved during thalium stress test. exang is whether angina is exercied induced or not. oldpeak is ST depression induced by exercise relative to rest. slope is slope of peak exercise ST segment. ca is the number of major vessels colored by fluroscopy. thal is the thalium stress test result (normal, fixed defect, or reversible defect). target is whether a patient has a heart disease (y=0: heart disease;y=1: no). 
#1. (15 pts) Perform a MANOVA testing whether any of your numeric variables(or a subset of them, if including them all doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find responses(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which group differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), ad adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2). 
```{R}
#MANOVA
man1<-manova(cbind(trestbps,chol,thalach,oldpeak)~cp,data=heart)
summary(man1)
#univariate ANOVA
summary.aov(man1)
heart%>%group_by(cp)%>%
  summarize(mean(trestbps),mean(chol), mean(thalach),mean(oldpeak))
#t tests
pairwise.t.test(heart$trestbps,heart$cp,p.adj="none")
pairwise.t.test(heart$chol,heart$cp,p.adj="none")
pairwise.t.test(heart$thalach,heart$cp,p.adj="none")
pairwise.t.test(heart$oldpeak,heart$cp,p.adj="none")
1-.95^(21)
```
1 MANOVA, 4 ANOVA 12 t-tests, all of which sum up to total of 21 tests. The probability of at least one type I error is .659. The adjusted significance level is 0.05/21 = 0.0024.
The maximum heart rate achieved during thalium stress test is different across the levels, more specifically, chest pain type 0 differs from the other three (0 vs 1, 0 vs 2, 0 vs 3). ST depression induced by exercise relative to rest is different (0 vs 1, 0 vs 2, 1 vs 3).
Random sample assumption is most likely not met since the samples were collected. Samples were independent and large enough (25+). Equal variance.
#2. (10 pts) Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distirbution and the test statistic (3). 
```{R}
ggplot(heart,aes(chol,fill=sex))+geom_histogram(bins=6.5)+facet_wrap(~sex,ncol=2)+theme(legend.position="none")
heart%>%group_by(sex)%>%
  summarize(means=mean(chol))%>%summarize(`mean_diff:`=diff(means))
perm1<-data.frame(sex=heart$sex,chol=sample(heart$chol))
perm1%>%group_by(sex)%>%
  summarize(means=mean(chol))%>%summarize(`mean_diff:`=diff(means))
perm2<-data.frame(sex=heart$sex,chol=sample(heart$chol)) 
perm2%>%group_by(sex)%>%
  summarize(means=mean(chol))%>%summarize(`mean_diff:`=diff(means))
perm3<-data.frame(sex=heart$sex,chol=sample(heart$chol)) 
perm3%>%group_by(sex)%>%
  summarize(means=mean(chol))%>%summarize(`mean_diff:`=diff(means))
rand_dist<-vector()
for(i in 1:5000){
new<-data.frame(chol=sample(heart$chol),sex=heart$sex)
rand_dist[i]<-mean(new[new$sex==0,]$chol)-
 mean(new[new$sex==1,]$chol)}
{hist(rand_dist,main="",ylab=""); abline(v = -22.01,col="red")}
mean(rand_dist>22.01)*2
t.test(data=heart,chol~sex)
obs_F<-22.01
Fs<-replicate(5000,{
 new<-heart%>%mutate(chol=sample(chol))
 SSW<- new%>%group_by(sex)%>%summarize(SSW=sum((chol-mean(chol))^2))%>%
   summarize(sum(SSW))%>%pull
 SSB<- new%>%mutate(mean=mean(chol))%>%group_by(sex)%>%
   mutate(groupmean=mean(chol))%>%
 summarize(SSB=sum((mean-groupmean)^2))%>%summarize(sum(SSB))%>%pull
 (SSB/2)/(SSW/57)})
hist(Fs, prob=T); abline(v = obs_F, col="red",add=T)
```
Null: mean cholesterol level is the same for female vs. male patients. Alternative: mean cholesterol level is different for female vs. male patients. We can reject the null hypothesis as the mean choleterol level is significantly different for female vs. male patients. 
#3. (35 pts) Build a linear regression model prediciting one of your response variables from at least 2 other variables, including their interactions. Mean-center any numeric variables involved in the interaction. Interpret the coefficient estimates (do not discuss significance) (10) Plot the regression using ggplot(). If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (7) Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (3) Regardless, recompute regression results with robust standard errors via coeftest(..., vcov=vcovHC(...)). Discuss significance of results, including any changes from before/after robust SEs if applicable. (7) What proportion of the variation in the outcome does your model explain? (3)
```{R}
fit<-lm(chol ~ trestbps + thalach, data=heart)
summary(fit)
qplot(x = thalach, y = chol, data = heart) +
 stat_smooth(method = "lm", se = FALSE, fullrange = TRUE)
heart<-heart%>%mutate(thalach_c=thalach-mean(thalach),   trestbps_c=trestbps-mean(trestbps))
fit1<-lm(chol~trestbps_c*thalach_c,data=heart)
summary(fit1)
resids<-fit1$residuals
fitvals<-fit1$fitted.values
#Linearity and homoskedasticity look normal. 
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col="red")
library(lmtest)
bptest(fit1)
#normality looks normal.
ggplot()+geom_histogram(aes(resids),bins=20)
ggplot()+geom_qq(aes(sample=resids))+geom_qq_line(aes(sample=resids), color='red')
#hypothesis test
ks.test(resids, "pnorm", mean=0, sd(resids))
#robust SEs 
library(sandwich)
summary(fit1)$coef[,1:2]
coeftest(fit1, vcov=vcovHC(fit1))[,1:2]
#Proportion of the variation explained by the model 
summary(fit1)$r.sq
```
While controlling for trestbps, thalach does not explain variation.
While controlling for thalach, trestbps does not explain variation. 
199.8 is the predicted value of cholesterol level when trestbps and thalch are zero. .3634 is the slop for trestbps on chol while holding thalach constant. -.009497 is the slop for thalach on chol while holding trestbps constant. 
After the robust SEs, intercept:2.97,trestbps_c:.157,thalach_c: .115,trestbps_c:thalach_c:.00725.
#4. (5 pts) Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)
```{R}
fit1<-lm(chol~trestbps_c*thalach_c,data=heart)
samp_distn<-replicate(5000, {
 boot_dat<-heart[sample(nrow(heart),replace=TRUE),]
 fit1<-lm(chol~trestbps_c*thalach_c,data=boot_dat)
 coef(fit1)})
## Estimated SEs
samp_distn%>%t%>%as.data.frame%>%summarize_all(sd)
```
Intercept: ->2.96, trestbps_c: ->.161, thalach_c: ->.115, trestbps_c:thalach_c: ->.00718. 
#5. (40 pts) Perform a logistic regression predicting a binary categorical variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary). Interpret coefficient estimates in context (10) Report a confusion matrix for your logistic regression (2) Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5) Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3) Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (10) Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)
```{R}
class_diag<-function(probs,truth){
 tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
 acc=sum(diag(tab))/sum(tab)
 sens=tab[2,2]/colSums(tab)[2]
 spec=tab[1,1]/colSums(tab)[1]
 ppv=tab[2,2]/rowSums(tab)[2]
 if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1
 ord<-order(probs, decreasing=TRUE)
 probs <- probs[ord]; truth <- truth[ord]
 TPR=cumsum(truth)/max(1,sum(truth))
 FPR=cumsum(!truth)/max(1,sum(!truth))
 dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
 TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
 n <- length(TPR)
 auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
 data.frame(acc,sens,spec,ppv,auc)} 
#logistic regression
odds<-function(x)x/(1-x)
x<-seq(0,1,by=.1)
cbind(x, odds=odds(x))%>%round(4)
logit<-function(x)log(odds(x))
cbind(x, odds=odds(x),logit=logit(x))%>%round(4)
logfit<-glm(target~sex+cp,data=heart,family=binomial(link="logit"))
coeftest(logfit)
exp(coeftest(logfit))
#confusion matrix
prob<-predict(logfit,type="response")
pred<-ifelse(prob>.5,1,0)
table(prediction=pred,truth=heart$target)%>%addmargins
#Accuracy
(90+119)/303 
#Sensitivity(TPR)
119/165
#Specificity(TNR)
90/138
#Precision(PPV)
119/167
#density plot of log-odds
heart$logit<-predict(logfit)
heart$outcome<-factor(heart$target,levels=c(1,0))
ggplot(heart,aes(logit, fill=outcome))+geom_density(alpha=.3)
#ROC and AUC
heart$prob<-predict(logfit,type="response")
sens<-function(p,data=heart, y=target) mean(heart[heart$target==1,]$prob>p)
spec<-function(p,data=heart, y=target) mean(heart[heart$target==0,]$prob<p)
sensitivity<-sapply(seq(0,1,.01),sens,heart)
specificity<-sapply(seq(0,1,.01),spec,heart)
ROC1<-data.frame(sensitivity,specificity,cutoff=seq(0,1,.01))
ROC1$TPR<-sensitivity
ROC1$FPR<-1-specificity
ROC1%>%ggplot(aes(FPR,TPR))+geom_path(size=1.5)+geom_segment(aes(x=0,y=0,xend=1,yend=1),lty=2)+scale_x_continuous(limits = c(0,1))

ROCplot<-ggplot(heart)+geom_roc(aes(d=target,m=prob), n.cuts=0)+
 geom_segment(aes(x=0,xend=1,y=0,yend=1),lty=2) 
calc_auc(ROCplot)
#10-fold CV
set.seed(1234)
k=10
data<-heart[sample(nrow(heart)),]
folds<-cut(seq(1:nrow(heart)),breaks=k,labels=F) 
diags<-NULL
for(i in 1:k){
 train<-data[folds!=i,]
 test<-data[folds==i,]
 truth<-test$target
 fit<-glm(target~sex+cp,data=heart,family="binomial")
 probs<-predict(fit,newdata = test,type="response")
 diags<-rbind(diags,class_diag(probs,truth))}
apply(diags,2,mean)
```
Controlling for cp, sex and target are not significantly different. 
Controlling for sex, cp and target are not significantly different. 
AUC is 0.787 (fair and close to good), which is not good enough to predict whether a paitent has a heart disease only from sex and chest pain type. 
Accuracy and Sensitivity after 10-fold CV are .689 and .721, respectively. 
#6. (10 pts) Choose one variable you want to predict (can be one you used from before; either binary or continuous) and run a LASSO regression inputting all the rest of your variables as predictors. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., lambda.1se). Discuss which variables are retained. Perform 10-fold CV using this model: if response in binary, compare model’s out-of-sample accuracy to that of your logistic regression in part 5.
```{R}
y<-as.matrix(heart$target)
x<-heart%>%dplyr::select(-target,-logit,-outcome,-prob)%>%mutate_all(scale)%>%as.matrix
cv<-cv.glmnet(x,y)
lasso<-glmnet(x,y,lambda=cv$lambda.1se)
coef(lasso)

fit<-lm(target~.,data=heart)
yhat<-predict(fit)
mean((heart$target-yhat)^2)

set.seed(1234)
k=10
data1<-heart[sample(nrow(heart)),] 
folds<-cut(seq(1:nrow(heart)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
 train<-data1[folds!=i,]
 test<-data1[folds==i,]
 fit<-lm(target~sex+cp+thalach+exang+oldpeak+slope+ca+thal,data=train)
 yhat<-predict(fit,newdata=test)
 diags<-mean((test$target-yhat)^2)} 
mean(diags)

set.seed(1234)
k=10
data<-heart[sample(nrow(heart)),]
folds<-cut(seq(1:nrow(heart)),breaks=k,labels=F) 
diags<-NULL
for(i in 1:k){
 train<-data[folds!=i,]
 test<-data[folds==i,]
 truth<-test$target
 fit<-glm(target~sex+cp+thalach+exang+oldpeak+slope+ca+thal,
          data=heart,family="binomial")
 probs<-predict(fit,newdata = test,type="response")
 diags<-rbind(diags,class_diag(probs,truth))
}
apply(diags,2,mean)
```
Based on the lasso regression, sex, cp, thalach, exang, oldpeak, slope, ca, and thal are retained. Compared to the log regression model from the previous questions, AUC has become much better (AUC = .912) along with accuracy (ACC = .851). Also the mean squared error has become a lot smaller (MSE = 0.0962), which means it's much better. 